# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



### Task:

In [1]:
import numpy as np

Print the version and configuration of the library:

In [2]:
np.__version__


'1.23.5'

In [3]:
np.show_config


<function numpy.__config__.show()>

Create a vector of 10 elements filled with 1:

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create a vector with values from 0 to 10:

In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a 5 by 5 matrix filled with zeros:

In [6]:
n_vect = np.zeros(25).reshape((5, 5))
n_vect

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Fill the vector of 20 elements with random integers. Find the indices of non-zero elements:

In [7]:
arr = np.random.randint(1, 101, 20)
non_zero_indices = np.nonzero(arr)

print("A vector with random integers:", arr)
print("\nIndexes of non-zero elements:", non_zero_indices)

A vector with random integers: [24 13 80 92 79 25 50 44  9 59 98  1 20 72 62 88 29 66 47 41]

Indexes of non-zero elements: (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


For the vector from the previous problem, find the mean, median, and standard deviation:

In [8]:
print('Mean: ', np.mean(arr))
print('Median: ', np.median(arr))
print('Standard deviation: ', np.std(arr))

Mean:  49.95
Median:  48.5
Standard deviation:  28.667882726144946


Create two matrices of random numbers of size 4x2 and 2x2. Multiply them:

In [9]:
mtrx1 = np.random.random((4,2))
print('The generated matrix #1:\n', mtrx1)

mtrx2 = np.random.random((2,2))
print('\nThe generated matrix #2:\n', mtrx2)

multipl_mtrx = np.dot(mtrx1, mtrx2)
print('\nThe multiplied matrix:\n', multipl_mtrx)

The generated matrix #1:
 [[0.52015875 0.90907089]
 [0.89404606 0.54015894]
 [0.32947242 0.13492033]
 [0.5430015  0.34452752]]

The generated matrix #2:
 [[0.85300946 0.1850372 ]
 [0.15774    0.49394209]]

The multiplied matrix:
 [[0.58709718 0.54527709]
 [0.84783442 0.43223901]
 [0.30232542 0.12760748]
 [0.51753119 0.27065212]]


Convert the resulting matrix from the previous problem to a vector. Find the minimum and maximum values. 

Replace the maximum value with 0:

In [10]:
vector = multipl_mtrx.flatten()

min_value = np.min(vector)
max_value = np.max(vector)

vector[vector == max_value] = 0

print("Min value:", min_value)
print("Max value:", np.max(vector))

Min value: 0.12760748480632603
Max value: 0.5870971764472411


Find the correlation of the first row of the matrix from the previous problem with the other rows:

In [11]:
first_row = multipl_mtrx[0]

correlation_matrix = np.corrcoef(multipl_mtrx)

correlation_with_first_row = correlation_matrix[0]

print("Correlation matrix:")
print(correlation_matrix)

print("Correlation of the first row with other rows:")
print(correlation_with_first_row)

Correlation matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Correlation of the first row with other rows:
[1. 1. 1. 1.]


The matrix is given. Find the rank of the matrix:

In [12]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

rank = np.linalg.matrix_rank(a)
print("Rank:", rank)

Rank: 3


Find the determinant of a matrix:

In [13]:
determinant = np.linalg.det(a)
print("Determinant of a matrix:", determinant)

Determinant of a matrix: 440.0000000000002


Find the eigenvalues and eigenvectors of the matrix:

In [14]:
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues:\n", eigenvalues)
print("\n Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]

 Eigenvectors:
 [[ 0.43131913+0.j          0.31386258+0.47450898j  0.31386258-0.47450898j]
 [ 0.41502436+0.j          0.07049527-0.4090732j   0.07049527+0.4090732j ]
 [ 0.8010734 +0.j         -0.7099444 +0.j         -0.7099444 -0.j        ]]


Find the number that occurs most often in the array:

In [15]:
a = np.random.randint(0,10,50)
most_common_number = np.argmax(np.bincount(a))
print("Array:", a)
print("The most frequently occurring number:", most_common_number)

Array: [0 0 9 5 6 7 5 9 6 8 7 0 4 0 5 9 0 0 4 3 8 2 7 4 3 5 9 8 1 1 1 5 8 8 1 3 0
 5 9 4 6 0 1 2 2 8 7 9 9 0]
The most frequently occurring number: 0


Print only even numbers divisible by 5:

In [16]:
a = np.random.randint(0, 50, 50)

result = []

for number in a:
    if number != 0 and number % 2 == 0 and number % 5 == 0:
        result.append(number)

print("Array:", a)
print("Even numbers divisible by 5:", result)

Array: [31 10 23 39 45 11 20 23 33 16 42  1 31 11  4  8  3 37 41  2 24 35 25 27
 34 15 48  7  4 11 39 43 17  7 35 23 25  5 47 20  6 25 39 27 33 16 45 20
  5 43]
Even numbers divisible by 5: [10, 20, 20, 20]


Solve the system of equations:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [17]:
A = np.array([[2, 5],
              [1, -10]])

B = np.array([1, 3])

solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]

print(f"x = {x}")
print(f"y = {y}")

x = 1.0
y = -0.2
